Repository Rancho2002/C-projects, pull requests merged in 2022-10, with the labels that each got.

#2 Mini-Voting-system
  Mini-Voting-System/Election.h
  Mini-Voting-System/Main.c
  Mini-Voting-System/readme.md
Labels: good first issue, hacktoberfest-accepted

#7 Added Guess the number game
  Guess the number/guess_game.c
  Guess the number/readme.md
Labels: good first issue

#9 Added snake, water, gun game
  Snake, Water, Gun game/readme.md
  Snake, Water, Gun game/snake_game.c
Labels: hacktoberfest-accepted, hacktoberfest

#10 Sarthak Aggarwal
  .DS_Store
  Matrix-Calculator/.DS_Store
  Matrix-Calculator/README.md
  Matrix-Calculator/main.c
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#11 Traffic Control Project
  Library Management/library-management-project-in-c-programming.png
  Library Management/main.c
  Library Management/readme.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#14 ATM Machine
  ATM-machine/CProgram.c
  ATM-machine/readme.md
Labels: hacktoberfest-accepted, hacktoberfest

#16 Calendar Project written entirely in C
  Calendar With C/Readme.md
  Calendar With C/calendar.c
Labels: hacktoberfest-accepted, hacktoberfest

#17 Added File Compressor
  Space, newline ommiter/compress.txt
  Space, newline ommiter/file_compressor.c
  Space, newline ommiter/file_compressor.exe
  Space, newline ommiter/index.html
  Space, newline ommiter/readme.md
Labels: hacktoberfest-accepted, hacktoberfest

#21 Added bank management system
  Bank Management System/Bank.C
  Bank Management System/Readme.md
  Bank Management System/images/1.png
  Bank Management System/images/10.png
  Bank Management System/images/2.png
  Bank Management System/images/3.png
  Bank Management System/images/4.png
  Bank Management System/images/5.png
  Bank Management System/images/6.png
  Bank Management System/images/7.png
  Bank Management System/images/8.png
  Bank Management System/images/9.png
Labels: hacktoberfest-accepted, hacktoberfest

#26 Added Employee Management System c project
  Employee-Management-System/Employee Management System-github.c
  Employee-Management-System/README.md
Labels: hacktoberfest-accepted, hacktoberfest

#27 Created License and Code-Of-Conduct.
  CODE_OF_CONDUCT.md
  LICENSE
Labels: hacktoberfest-accepted, hacktoberfest

#24 Adds Grep Command Project developed in the C
  Grep_Project/Makefile
  Grep_Project/README.md
  Grep_Project/Screenshots/A.png
  Grep_Project/Screenshots/H.png
  Grep_Project/Screenshots/L.png
  Grep_Project/Screenshots/Li.png
  Grep_Project/Screenshots/b.png
  Grep_Project/Screenshots/c.png
  Grep_Project/Screenshots/cv.png
  Grep_Project/Screenshots/h.png
  Grep_Project/Screenshots/help.png
  Grep_Project/Screenshots/i.png
  Grep_Project/Screenshots/in.png
  Grep_Project/Screenshots/l.png
  Grep_Project/Screenshots/li.png
  Grep_Project/Screenshots/m.png
  Grep_Project/Screenshots/n.png
  Grep_Project/Screenshots/normal.png
  Grep_Project/Screenshots/r.png
  Grep_Project/Screenshots/ri.png
  Grep_Project/Screenshots/rv.png
  Grep_Project/Screenshots/standard_i.png
  Grep_Project/Screenshots/standard_input.png
  Grep_Project/Screenshots/standard_v.png
  Grep_Project/Screenshots/standard_vi.png
  Grep_Project/Screenshots/v.png
  Grep_Project/Screenshots/vn.png
  Grep_Project/Screenshots/w.png
  Grep_Project/dir.c
  Grep_Project/grep.c
  Grep_Project/header.h
  Grep_Project/mystrstr.c
  Grep_Project/mystrstrcase.c
  Grep_Project/mystrtok_multi.c
  Grep_Project/standard_input.c
  Grep_Project/standard_options.c
  Grep_Project/test_dir/header.h
  Grep_Project/test_dir/test/header.h
  Grep_Project/test_dir/test/test2/header.h
  Grep_Project/test_dir/test/test2/testfile.test
  Grep_Project/test_dir/test/testfile.test
  Grep_Project/test_dir/testfile.test
  Grep_Project/testfile.test
  Grep_Project/usage.c
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#29 Playback Speed Calculator
  Readme.md
  sourceCode.c
Labels: hacktoberfest-accepted, hacktoberfest

#15 Added Tic-Tac-Toe Project
  Tic-Tac-Toe/README.md
  Tic-Tac-Toe/score.txt
  Tic-Tac-Toe/tic-tac-toe.c
Labels: good first issue, progress

#28 password_generator
  password_generator/main.c
  password_generator/readme.md
Labels: good first issue

#22 Added Phonebook Project in C
  Phonebook-C-Project/README.md
  Phonebook-C-Project/abc.txt
  Phonebook-C-Project/phonebook.c
  Phonebook-C-Project/phonebook.exe
  Phonebook-C-Project/sample.txt
  Phonebook-C-Project/screenshots/front.jpg
  Phonebook-C-Project/screenshots/main.jpg
Labels: progress
